ORG 40H
	
BIN2ASCII:
	
	USING 0
	PUSH PSW
	PUSH AR4
	PUSH AR3
	PUSH AR2
	PUSH AR1
	PUSH AR0
	MOV R2, 50H; VALUE OF N
	MOV R0 , 51H; VALUE OF READ POINTER
	MOV R1 , 52H; VALUE OF WRITE POINTER


	LOOP_BIN2ASCII:
	MOV A, @R0;
	MOV R3, A;  TEMPORARILY STORING THE VALUE OF A
	ANL A, #0FH ; MAKING THE UPPER NIBBLE 0000
	MOV R4, A; STORING THE LOWER NIBBLE
	
	SUBB A, #0AH ; TO CHECK IF THE LOWER NIBBLE IS DIGIT OR ALPHABET
	JNC ALPHA ;-- if carry is not set then the nibble was an alphabet
	
	MOV A, R4;
	ADD A, #30H ; ESLE ITS A DIGIT; CONVERTING THE LOWER NIBBLE TO ASCII
	INC R1
	MOV @R1, A
	DEC R1
	JMP NEXT
	
	ALPHA: MOV A, R4;
	ADD A, #37H
	INC R1
	MOV @R1,A
	DEC R1
	
	NEXT:
	MOV A, R3;
	ANL A,#0F0H ; MAKING THE LOWER NIBBLE 0000
	SWAP A; SWAPPING THE UPPER AND LOWER NIBBLE
	MOV R4,A; TEMPORARILY STORING THE UPPER NIBBLE
	SUBB A, #0AH
	JNC BETA ;-- if carry is not set then the nibble was an alphabet

	MOV A,R4
	ADD A, #30H ;ELSE THE NIBBLE IS A DIGIT
	
	MOV @R1,A
	INC R1
	JMP NEXT1
	
	BETA: MOV A, R4;
	ADD A, #37H
	MOV @R1,A
	INC R1
	
	NEXT1:
	INC R0
	INC R1
	DJNZ R2, LOOP_BIN2ASCII
	
	POP AR0
	POP AR1
	POP AR2
	POP AR3
	POP AR4
	POP PSW
	
	RET
	
END	